baseURL = "https://ritvik-teegavarapu.com"
languageCode = "en-us"
title = "Ritvik Teegavarapu"
theme = "hugo-xmin"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Incoming PhD student in Applied Mathematics @ Brown University"
  footer = "© 2026 Ritvik Teegavarapu"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

[[menu.main]]
  name = "Presentations"
  url = "/presentations/"
  weight = 4

  [[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 5

[[menu.main]]
  name = "Mentoring"
  url = "/mentoring/"
  weight = 6

  [[menu.main]]
  name = "Outreach"
  url = "/outreach/"
  weight = 7

[[menu.main]]
  name = "Bookshelf"
  url = "/bookshelf/"
  weight = 8

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 9